parti-renaissance/espace-cadre

- src/components/Contacts/Contacts.jsx
- src/components/Root/Root.jsx
- src/components/Sidebar/Sidebar.jsx
- src/components/Spinner/Spinner.jsx
1. Fix the infinite spinner
2. Move welcome message in sidebar
> Contacts page improvements

- src/components/Mail/Audience/Audience.jsx
- src/components/Mail/Mail.scss
- src/components/Mail/Template/Template.jsx
- src/components/Mail/Template/Template.scss
- src/components/Mail/Template/grapesjs/Config.js
- src/components/Mail/Template/grapesjs/Editor.jsx
- src/components/Mail/Template/grapesjs/Editor.scss
- src/services/networking/client.js
Update de l'éditeur avec typo intégrée au panel par le bouton pinceau
> Editors Changes / Template empty and Blocks

- src/components/ContactsPage/ColumnsContentRendering/InterestRendering/InterestRendering.jsx
- src/components/ContactsPage/ColumnsContentRendering/InterestRendering/InterestRendering.scss
- src/components/ContactsPage/Table/Table.jsx
- src/components/ContactsPage/Table/Table.scss
> Style for page Contacts

- package.json
- src/components/Mail/Mail.jsx
- src/components/Mail/Mail.scss
- src/components/Mail/Template/Template.jsx
- src/components/Mail/Template/Template.scss
- src/components/Mail/Template/grapesjs/Config.js
- src/components/Mail/Template/grapesjs/Config.scss
- src/components/Mail/Template/grapesjs/Editor.jsx
- src/components/Mail/Template/grapesjs/Editor.scss
- yarn.lock
> Send mailP

- webpack.config.js
- yarn.lock
Pour ouvrir l'app dans le browser la compil, rajouter dans le .env.local :
CONFIG_DEV_SERVER_OPEN=true
> [TECH] Dev server open page

- src/components/Dashboard/Map/MapComponent.jsx
- webpack.config.js
https://em-tech-innovation.atlassian.net/browse/EM-1599
> fix leaflet icons

- src/components/Filters/Element/Autocomplete.js
> fix query separator

- package.json
- src/App.js
- src/components/Messagerie/Template.js
- src/components/Teams/TeamEdit.js
- src/components/Teams/TeamModal.js
- src/components/shared/messages.js
- src/notify.js
- yarn.lock
Affichage des notifications sur l'app Je m'engage
- Affichage snackbar
- Gestion success/error lors de call API
- Messages génériques
> [EM-1543] Notifs snackbar

- package.json
- src/components/Layout/Layout.js
- src/components/Messagerie/Template.js
- src/components/Teams/TeamEdit.js
- src/components/Teams/TeamModal.js
- src/components/shared/messages.js
- src/components/shared/notification/constants.js
- src/components/shared/notification/hooks.js
- src/notify.js
- src/redux/errors/index.js
- src/redux/errors/selectors.js
- src/redux/errors/slice.js
- src/redux/reducers/index.js
- src/services/networking/client.js
- src/theme.js
- src/ui/SnackBar/SnackBar.js
- yarn.lock
PR pour le catch des errors 500 depuis axios
Un snackbar d'error est affiché
> [EM-1543] Global errors

- src/api/dynamic.js
- src/components/Filters/Element/Autocomplete.js
- Debounce de l'input
- Création (temporaire) d'un endpoint "dynamic" pour les uri / params envoyés par le back
> [EM-1638] Debounce Autocomplete

- cypress/fixtures/ripostes/ripostes.json
- cypress/fixtures/scope/national.json
- cypress/integration/main.spec.js
- src/api/messagerie.js
- src/api/news.js
- src/api/ripostes.js
- src/components/Dashboard/Charts/SentEmailCampaignList/SentEmailCampaignList.js
- src/components/Dashboard/Charts/SentEmailCampaignList/card/Header.js
- src/components/News/News.js
- src/components/Ripostes/Card/Actions.js
- src/components/Ripostes/CreateEditModal.js
- src/components/Ripostes/Ripostes.js
- src/providers/styles.js
- src/ui/Card/Menu/DotsMenu.js
pagination riposte
fix pagination messagerie + news
> pagination riposte

- src/App.js
- src/components/Layout/Layout.js
- src/components/Messagerie/Component/Editor.js
- src/components/Messagerie/Template.js
- src/components/shared/error/hooks.js
- webpack.config.js
> improve sentry

- src/components/shared/error/hooks.js
> fix null data in response

- package.json
- yarn.lock
"@babel/preset-react": "7.16.7",
> "@babel/preset-env": "7.16.7",

- renovate.json
Dependabot is doing the job just right
> Proposition to delete Renovate from the repo

- src/api/messagerie.js
- src/components/Messagerie/Filters.js
Reverts EnMarche/Data-Corner#1244
> Revert "[Messages] replace segment endpoint by filter"

- src/api/messagerie.js
- src/components/Messagerie/Filters.js
Reverts EnMarche/Data-Corner#1269
> [Messages] replace segment endpoint by filter

- src/components/ElectedRepresentative/Dashboard.jsx
Reverts EnMarche/Data-Corner#2086
> Revert "Display contribution information based on contribution date"

- src/components/Layout/Desktop.jsx
- src/components/Layout/Footer.jsx
- src/components/Layout/Mobile.jsx
- src/components/Layout/Navigation.jsx
- src/components/Layout/Sidebar.jsx
- src/components/Scopes/Scopes.jsx
- src/style/_layout.scss
- src/style/partials/_utilities.scss
- src/ui/Button/Button.jsx
- src/ui/Logo/Logo.jsx
> update JME sidebar navigation

- src/components/Layout/NavMenu.jsx
- src/style/_buttons.scss
- src/style/_layout.scss
> Add button to toggle menu visibility

- package.json
- yarn.lock
Reverts EnMarche/Data-Corner#2102
> Revert "build(deps): bump @sentry/tracing from 7.45.0 to 7.47.0"
